name: qUHC
main: com.thesevenq.uhc.UHC
version: 1.0-SNAPSHOT
description: Sicaro UHC Core
author: thesevenq
depend: [ProtocolLib]
commands:
   autostart:
     description: Auto Start command
   wborder:
     description: Primary command for WorldBorder.
     aliases: [worldborder, wb]
   backpack:
     description: Backpack Command   
     aliases: [backpacks, bp]
   border:
     description: Border Command   
     aliases: []
   config:
     description: Config Command   
     aliases: []
   flat:
     description: Flat Command   
     aliases: []     
   health:
     description: Health Command   
     aliases: [h, hp]     
   hidelocation:
     description: Hidelocation Command   
     aliases: [hideloc]         
   killcount:
     description: KillCount Command   
     aliases: [kc]
   mlg:
     description: MLG Command         
   uhcpractice:
     description: UHCPractice Command   
     aliases: [uhcprac, prac, practice]
   multispawn:
     description: MultiSpawn Command
     aliases: [ms]
   nextgame:
     description: NextGame Command
     aliases: [ng, nextuhc, nu]
   onlinestaff:
     description: OnlineStaff Command   
     aliases: []
   revive:
     description: Revive Command   
     aliases: [staffrevive, srevive, respawn]
   scatter:
     description: Scatter Command   
     aliases: [latescatter]       
   scenarios:       
     description: Scenarios Command   
     aliases: [scenario]     
   stats:
     description: Stats Command   
     aliases: [status]        
   spectator:
     description: Spectator Command   
     aliases: [spec, mod, staffmode, modmode]     
   topkills:
     description: TopKills Command   
     aliases: [kt, tk, killtop]           
   game:
     description: UHC Command   
     aliases: [uhcsettings]                       
   whitelist:
     description: Whitelist Command   
     aliases: [wl]          
   party:
     description: Team Command   
     aliases: [team, t, fac, f, faction]
   partylist:
     description: TeamList Command   
     aliases: [tl, fl, teaml, tlist, teamlist]
   xray:
     description: XRay Command   
     aliases: [togglexrayalerts, togglefd, fd, tfd]
   deathlookup:
     description: Deathlookup Command
     aliases: [dl, deathl, dlookup, deathlook, lookdeath]
   lastinventory:
     description: Lastinventory Command
     aliases: [li, lastinv, lastinventory, restoreinv, restoreinventory, ri]
   leaderboard:
     description: Leaderboard Command
     aliases: [lb, leaderboards, leaderb, lboard]
   clearlagg:
     description: Clear Lag Cmd
     aliases: [lagg]